import {
  LayoutDashboard,
  Users,
  Clock,
  Wallet,
  Briefcase,
  LineChart,
  Folder,
  BarChart2,
  Settings,
  List,
  Shield,
  Layers,
  LogIn,
  Calendar,
  DollarSign,
  File,
  CreditCard,
  Target,
  CheckSquare,
  FileText,
  User,
  Lock,
  Menu
} from 'lucide-react';

export const iconMap = {
  'dashboard': LayoutDashboard,
  'users': Users,
  'clock': Clock,
  'wallet': Wallet,
  'briefcase': Briefcase,
  'chart': LineChart,
  'folder': Folder,
  'bar-chart': BarChart2,
  'settings': Settings,
  'list': List,
  'shield': Shield,
  'layers': Layers,
  'log-in': LogIn,
  'calendar': Calendar,
  'dollar': DollarSign,
  'file': File,
  'credit-card': CreditCard,
  'target': Target,
  'check-square': CheckSquare,
  'file-text': FileText,
  'user': User,
  'lock': Lock,
  'menu': Menu
};
